# Dependencies
highlighter:      rouge

plugins:
  - jekyll-paginate
  - jekyll-feed

# Permalinks
permalink:              /blog/:categories/:title/
# permalink:            blog/:categories/:year/:month/:day/:title/

# Setup
title:            'Anjana Sofia Vakil'
name:             'Anjana Sofia Vakil'
#tagline:          ''
description:      'Developer Educator & Software Engineer'
#url:              http://vakila.github.io/
baseurl:          '/'
blogurl:          '/blog'

# Assets
images:         '/img'
pdfs:           '/pdf'

author:
  name:           'Anjana Sofia Vakil'
  url:            anjana.dev
  email:          'contact@anjana.dev'
  github:         'https://github.com/vakila'
  facebook:       ''
  twitter:        'https://twitter.com/AnjanaVakil'
  googleplus:     ''
  linkedin:       'https://www.linkedin.com/in/anjanavakil '

paginate:         10
paginate_path:    "/blog/page:num/"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/vakila/vakila.github.io

# Collections
collections:
  projects:
    output: false
  talks:
    output: false
  redirects:
    output: true
    permalink: /:name

# defaults:
#   -
#     scope:
#       path: ""
#       type: "projects" # a collection in your site, in plural form
#     values:
#       layout: "default"
